%% Data in for Empirical Study I  
% Bloom (2009)
% 1962/7:2008/6
clc
clear all
close all
%% Data transformation to the small one (already seasonally adj except for FF)

W = readtable('VARDATA.xlsx','Sheet','VARDATA','Range', 'J:R'); 	% shock indicator 
WDescr = {'actual volatility series','stock market volatility indicator',... 
    'S&P500 stock market index',... 
    'average hourly earnings for production workers (manufacturing)',...
    'consumer price index (all urban consumers)',...
    'average hours in manufacturing',...
    'employment in manufacturing',...
    'industrial production in manufacturing',...
    'federal fund rate',...
    'HP=c', 'log=l'};
W = rmmissing(W);

S1 = readtable('VARDATA.xlsx','Sheet','S1_Out','Range','J:M');
S1Descr = {'indicator with 60 windows and pce index',...
    'indicator with 60 windows and pce percapita',...
    'indicator with 30 windows and pce index',...
    'indicator with 30 windows and pce percapita',...
    '0==bad infaltion','1==good inflation'
    };
S1 = S1(1:552,:);

S2 = readtable('VARDATA.xlsx','Sheet','S2_Out','Range','B:D');
S2Descr = {'indicator with HH Survey from 1978',...
    'indicator with HH Survey from 1981',...
    'indicator with Professional Survey from 1981',...
    '0==unachored','1==anchored'
    }; % shorter sample than S1, S3 
% SPF is shorter than Michingan: 44:367 
S2 = S2(1:366,:);

S3 = readtable('VARDATA.xlsx','Sheet','S3_Out','Range','G:I');
S3Descr = {'indicator with deviation-from-target gap',...
    'indicator with rolling using CPI',...
    'indicator above 75th percentil volatility',...
    '0==high volatility infaltion','1==low volatility inflation'
    };
S3 = S3(1:552,:);

Data.W = W;
Data.S1 = S1;
Data.S2 = S2;
Data.S3 = S3;

save Empirical_Study\Data_EMP Data WDescr S1Descr S2Descr S3Descr;